version: 2.1

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@3.1.1
  slack: circleci/slack@4.12.5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-key: "node-modules-{{ checksum 'package-lock.json' }}-v2"
          pkg-manager: npm
      - run:
          name: Security Audit
          command: npm audit --production --audit-level=high
      - run:
          name: Run Tests with Coverage
          command: npm test -- --passWithNoTests --coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          destination: coverage-report

  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - node/install-packages:
          pkg-manager: npm
          args: --force
      - run:
          name: Fix Vulnerabilities
          command: npm audit fix --force || true
      - run:
          name: Update Dependencies
          command: npm update --save
      - run:
          name: Build Project
          command: npm run build
 
  build-and-push-docker:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10
          docker_layer_caching: true
      
      # Build with security flags
      - run:
          name: Build Secure Image
          command: |
            docker build \
              --pull \
              --no-cache \
              --build-arg NODE_ENV=production \
              -t $DOCKERHUB_USERNAME/zomato_clone:latest \
              -t $DOCKERHUB_USERNAME/zomato_clone:$CIRCLE_SHA1 .
      
      # Trivy Vulnerability Scan
      - run:
          name: Run Trivy Scan
          command: |
            trivy image \
              --severity CRITICAL,HIGH \
              --ignore-unfixed \
              --exit-code 1 \
              --cache-dir ~/.cache/trivy \
              --format json \
              --output trivy-scan.json \
              $DOCKERHUB_USERNAME/zomato_clone:latest
      - store_artifacts:
          path: trivy-scan.json
          destination: trivy-report
      
      # Docker Scout Analysis
      - run:
          name: Run Docker Scout
          command: |
            docker-scout cves \
              --exit-code \
              --only-severity critical,high \
              $DOCKERHUB_USERNAME/zomato_clone:latest > scout-report.txt
      - store_artifacts:
          path: scout-report.txt
          destination: scout-report
      
      # Secure Push
      - docker/check:
          docker-username: $DOCKERHUB_USERNAME
          docker-password: $DOCKERHUB_PASSWORD
      - docker/push:
          image: $DOCKERHUB_USERNAME/zomato_clone
          tag: "latest,$CIRCLE_SHA1"

workflows:
  main:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
      - build-and-push-docker:
          requires:
            - build-node
      - build-and-push-docker:
          context: docker-creds
          requires:
            - test-node