name: CI Pipeline

on:
  push:
    branches: [git-actions]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --passWithNoTests

  build-node:
    needs: test-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: |
            build
            dist
            public
            .output
            .next
            .docusaurus
          if-no-files-found: ignore

  build-and-push-docker:
    needs: build-node
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t $DOCKERHUB_USERNAME/zomato_clone:latest .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          trivy --version

      - name: Scan Docker Image with Trivy
        run: |
          mkdir -p ~/.cache/trivy
          trivy image --severity CRITICAL,HIGH --cache-dir ~/.cache/trivy --format json --output trivy-report.json $DOCKERHUB_USERNAME/zomato_clone:latest
        continue-on-error: true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sudo sh -s -- -b /usr/local/bin
          docker-scout version

      - name: Scan with Docker Scout
        run: |
          docker-scout cves $DOCKERHUB_USERNAME/zomato_clone:latest --only-severity critical,high > scout-report.txt
        continue-on-error: true

      - name: Upload Scout Report
        uses: actions/upload-artifact@v4
        with:
          name: scout-report
          path: scout-report.txt

      - name: Push Docker Image
        run: docker push $DOCKERHUB_USERNAME/zomato_clone:latest
